### PR TITLE
UI and Aesthetic improvements

### PR DESCRIPTION
**Pull request by sandertyu**
The primary function here was to make the site be less of an eyesore, apply some rough positioning, and quickly edit a few elements. The highlights are a background image ([source here](https://www.pexels.com/photo/white-bicycle-road-sign-686230/), the licence looks good but I'm not sure what else you would like to check), dropdown/figure/table centering, as well as fixing some widths on otherwise variable width elements. 

I cannot confirm whether or not this pull request will break some of the functionality. On my end, the plots are still messed up, but there have been no changes to any of the relevant callbacks in this branch. Even when I clone a new master repository and run the application from there I receive errors that I don't experience with the online version. I can continue to work on some additions like this - I'm looking to add units and more stylish table formatting - but I'll have to really buckle down and sort this issue out sooner or later.

### CODE REVIEW

**Comment by moorepants** [comment]
In general can you paste a screenshot here for changes that involve visuals?

**Comment by moorepants** [comment]
I just tried this out and it looks much nicer! But yes the graphs get all screwed up after I cycle through the bicycles. So you have some kind of bug there.

**Comment by moorepants** [comment]
On a widescreen, the figures do not stay centered:
image

**Comment by moorepants** [comment]
I can reproduce one image issue. 1) open app for the first time, 2) select fisher, 3) select crescendo, 4) select fisher and then the eigenvalue plot is empty.
image

**Comment by moorepants** [comment]
Merge in the current master branch to this one and see if the plots are fixed.

**Comment by moorepants** [comment]
You can't read the title:
image

Either change the font color or add some shading or a box behind it.

**Comment by sandertyu** [comment]
> Merge in the current master branch to this one and see if the plots are fixed.

This worked, I'm having absolutely no issues now. Thank you very much.

In the mean time, I've touched up the color scheme. I added slate colored borders around most of the elements, and changed the green colors to orange to match the leaves in the background.

I'm having a lot of difficulty consistently centering the plot images. I have the entire containing div for them centered, but when the viewport size changes, it just goes all over the place. I may have to try individual divs for each of them. I'll continue working on that, and then this pull request should be ready once that is submitted.

**Comment by moorepants** [comment]
We could merge this without the centering fixes. You can do that separately if you want. I can push this to the live app.

**Comment by moorepants** [comment]
It's working for me. I'm going to merge this as is and push to heroku.

**Pull request merged**
