### PR TITLE
Support Python 3

### PR DESCRIPTION
**Pull request by oliverlee**
All tests pass on my end and things seems to work when I import the module.

### CODE REVIEW

**Comment by moorepants** [comment]
Can you note this in the README, setup.py, and the release notes?

**Comment by moorepants** [comment]
We can make the next version 0.3.0.

**Comment by moorepants** [comment]
Also, we'll need to bump the Yeadon version dependency up to whatever we move that too.

**Comment by oliverlee** [comment]
Do you know how to change the yeadon dependency to a specific commit for now?

**Comment by moorepants** [comment]
I guess you could setup travis to clone yeadon and checkout a specific commit for the tests.

**Pull request merged**
