### PR TITLE
Added first draft of app explanation.

### PR DESCRIPTION
**Pull request by moorepants**
@sandertyu Here is a start for the explanation. It looks like there isn't a good default css color scheme.That will be fixed when you switch to bootstrap, but maybe there is a quick fix. I'm not sure how you were controlling colors.

### CODE REVIEW

**Comment by sandertyu** [comment]
Okay, it looks good to me. Pretty much all of the colors are controlled through styles.css in the assets folder. The [#version-bin](https://github.com/moorepants/BicycleParameters/blob/48fd3f575a6dab12b455b9e695d39c6d83bb06dd/bicycleparameters/assets/styles.css#L115) block in that file has pretty much all the formatting that I have been using for plain text.

**Comment by moorepants** [comment]
I updated the css to give some default text and link colors.

**Comment by sandertyu** [comment]
Okay, I was able to pull `app-explain` but I'm unable to test it because conda is not letting me install uncertainties. I've tried `conda install uncertainties` as well as `conda install -c conda-forge uncertainties` as suggested [here](https://anaconda.org/conda-forge/uncertainties). The error is as follows;


`(base) C:\Users\xyzasdf\Desktop\bike-lab\BicycleParameters>conda install -c conda-forge uncertainties`
`Collecting package metadata (current_repodata.json): done`
`Solving environment: failed with initial frozen solve. Retrying with flexible solve.`
`Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.`
`Collecting package metadata (repodata.json): done`
`Solving environment: failed with initial frozen solve. Retrying with flexible solve.`
`Solving environment: failed`

At this point it had been loading for like 10 minutes so I just interrupted the process. I searched online a little and couldn't find anything relevant, do you have any ideas how I could fix this?

**Comment by moorepants** [comment]
Try "conda update --all" then try installing uncertainties again.

**Comment by sandertyu** [comment]
That got it working. It seems to be a relatively common bug, I just ran your command and installed numpy from the base channel as suggested [here](https://stackoverflow.com/a/54344186).

Looking at this version, the first thing that pops out is that the text for the eigenvalue slider is the same color as the background, so it can't be read. I think in the past I had refrained from setting entire document colors because there was little enough elements where I was willing to style them individually. I also notice that the version box at the very bottom of the document just looks very awkwardly settled against the text. This would probably be best sorted out with the bootstraps update. I'm pretty confident I would be able to finish that by the end of next weekend, after finals are over.

**Comment by moorepants** [comment]
> I think in the past I had refrained from setting entire document colors because there was little enough elements where I was willing to style them individually.

You are supposed to set default values at the top level of the cascading style sheets and then style sub elements and groups of elements as you desire. You should also generally use classes over id tags to specifying the css layers. FYI

**Comment by moorepants** [comment]
I'm going to merge this one. I don't see the text color issue you mention. I think this is fine for now.

**Pull request merged**
