### PR TITLE
Transitioning to Bootstraps

### PR DESCRIPTION
**Pull request by sandertyu**
At the moment this is incomplete. I've managed to fit the most crucial elements onto one page for screens width 768px and larger. On smaller screens the elements will stack. We still need to review a final layout design, and some element positioning and styling remains to be done (such as that whole 'parameter set' box). I'm pushing it here so others can work on it as well. I've attached the single screen image below.
bike

### CODE REVIEW

**Comment by sandertyu** [comment]
Alright, here is a general positioning plan to get all the elements onto one page. Let me know what you think.

plan

I think it would look nice to have the eigenvalue slider and its title be inline with eachother. There's also some free space on right hand side at the bottom of the options column to the right of the eigenvalue slider. Not sure what to do with it. Otherwise, I think this positioning works very well.

**Comment by moorepants** [comment]
I like this! Nice work. I'm good with this design.

**Comment by sandertyu** [comment]
Okay, well having the design is good. However, I'm really not sure how to implement it. I added some spacing between the option elements on the right, but I'm trying to center them all within their column and it just isn't working. Additionally, I don't know how to place the eigenvalue slider right there in the empty space beneath the plots. I want it to be in the same bootstraps row as the tables, but then it would have to span multiple of the table columns... here's a photo of the current layout and I'll push the current code so you can take a look. 
full plots

(2 separate images)

w slider

**Comment by moorepants** [comment]
This basic layout should get you to a good starting point:

layout

**Comment by sandertyu** [comment]
Thank you for the drawing. What does `col-4` or `col-5` refer to? Should I be giving the bootstrap column elements that class name?

**Comment by moorepants** [comment]
`col-4` would be a col of width 4 (out of 12).

**Comment by moorepants** [comment]
Just get the column/row layout in place first. Don't add any other classes for justifying or vertical spacing, etc. Once you get the layout, show me a screen shot or push and we can discuss the adjustments.

**Comment by sandertyu** [comment]
I've pushed the most recent changes. Here is what it looks like live.

layout

**Comment by moorepants** [comment]
Here is what it looks like maximized on my 1920x1080 resolution laptop screen:
Selection_715

I think adding some vertical space between the primary rows is the only thing that is needed in terms of this layout to merge this. So some margin between the graphs and the tables and the table row and the markdown row.

If you want to fix this here, I think you should change the background of the slider to black and the text to match the font color of the rest of the text (white).

**Comment by moorepants** [comment]
Adding `className="my-2"` to each row works for me.

**Comment by moorepants** [comment]
One other issue. It seems you Container class is spanning the maximum width of the screen. I think that you want to have a maximum width on this so that it doesn't spread out too much on super wide screens. Maybe 1080px is a good maximum width.

**Comment by moorepants** [comment]
I think you want Fluid=False for container so it has controlled widths for different screen sizes.

**Comment by moorepants** [comment]
Here is what I see with `my-2` on each primary row and with container Fluid=False:
Selection_716

I think this is good.

**Comment by sandertyu** [comment]
Okay, I can change the title to a header and adjust the background color of the rangeslider. Is it possible for you to push to this branch so that I can pull your changes? The branch comes from my own fork so I'm not sure.

**Comment by moorepants** [comment]
I can push my changes.

**Comment by sandertyu** [comment]
Here is what it looks like now. This is by no means final, but I'l leave this here just so you can visualize the code that I changed (I do quite like the purple).

header title

**Comment by moorepants** [comment]
I like it. If you go with the purple it'd be good to use it in the other locations where there is accent too. You have a blue button, blue checkbox, light blue slider, etc. We can fix that in another PR though.

**Comment by sandertyu** [comment]
> I like it. If you go with the purple it'd be good to use it in the other locations where there is accent too. You have a blue button, blue checkbox, light blue slider, etc. We can fix that in another PR though.

Okay, I was thinking that might be confusing. If the button and the title are the same color, the user might believe the title is a button as well.

Also, are we meeting today with the same google hangouts link? I didn't receive any new link from you for our updated weekly meetings. @moorepants

**Comment by moorepants** [comment]
Selection_718

**Comment by sandertyu** [comment]
One thing I did was remove the max/minwidth styling that I had added to each of the datatables. They are now free to reflexively resize according to the width of their contents. Unfortunately, this has not fixed the overlapping issue in Edge/Firefox. Instead of the text overlapping into another column, the entire datatables just stack on top of eachother like so;
firefox-CYBORG

I have also noticed that depending on the theme I choose, different amounts of overlap will occur. I give a more full explanation [here](https://community.plotly.com/t/dash-datatable-has-a-different-width-in-different-web-browsers-while-using-dash-bootstraps-components/41599)on the community forums. This shouldn't be happening at all, because we have set the column widths to be 4 and 8, which add up to the total of 12. 

If no successful response is given from my forum post, I can go ahead and just try to wrap the text onto multiple rows. I'm not certain this would fix the issue though, because the datatables seem to be ignoring their column width specifications.

**Comment by moorepants** [comment]
@sandertyu What's the status here. I see you got some help from the forum.

**Comment by sandertyu** [comment]
The forum post alone did not fix the issue. I still had to allow for the text to overflow onto multiple lines. However, what they said about datatable and bootstraps each having their own version of row is correct: in the most recent version below, you'll see that the plots and datatable are the same distance from the edge of the screen whereas before they were not. This means it is being more properly treated as bootstraps styling now.

(what I see in chrome)
chrome

The overlapping issue has been fixed in firefox and other browsers. However, it is now positioning strangely as you can see

firefox

There are still a few styling and presentation issues that need to be fixed, but the app is workable and the elements are no longer overlapping and making eachother difficult to access. I think we can merge this and I will create a few issues about the remaining changes.

**Comment by moorepants** [comment]
This looks good! Let's merge. Let me see what Travis is failing.

**Comment by moorepants** [comment]
I pushed the lastest version to the live app. It's looking great!

**Pull request merged**
